# Generated by Django 5.2.6 on 2025-09-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_item_title_item_item_code_item_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='validQrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_qr', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='valid_qr',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
